"""Pytest-facing API boundary for the DNP3 master automation framework."""

from __future__ import annotations

from .client import Dnp3MasterClient
from .ems_test_plan import (
    EMS_TEST_PLAN_SCHEMA_VERSION,
    ControlCommand,
    ControlScenario,
    EmsTestPlan,
    EmsTestPlanError,
    PollScenario,
    UnsolicitedScenario,
    ValueExpectation,
    load_ems_test_plan,
)
from .ems_profile import (
    EMS_PICS_STATUSES,
    EMS_PROFILE_SCHEMA_VERSION,
    EmsDeviceIdentity,
    EmsProfile,
    EmsProfileError,
    load_ems_profile,
)
from .errors import (
    ClientStateError,
    Dnp3ClientError,
    HostCommandError,
    HostExitedError,
    HostProcessError,
    HostProtocolError,
    HostStartError,
    HostTimeoutError,
    SafetyIncidentAcknowledgmentError,
    SafetyIncidentConfigurationError,
    SafetyIncidentError,
    SafetyIncidentPersistenceError,
    UnresolvedSafetyIncidentError,
)
from .local_benchmark import (
    LOCAL_EVENT_PROFILE_SCHEMA_VERSION,
    LocalEventLoad,
    LocalEventProfile,
    LocalEventProfileError,
    load_local_event_profile,
    run_local_event_benchmark,
)
from .models import (
    AnalogOutputCommand,
    CaptureConfig,
    CaptureEventManifest,
    CapturePointRange,
    CaptureResult,
    CommandPointResult,
    CommandTaskResult,
    CrobCommand,
    HostProcessConfig,
    HostProcessDiagnostics,
    LabSafetyConfig,
    MeasurementRecord,
    ReadHeader,
    ReadTaskResult,
    TcpConnectionConfig,
    UnsolicitedBatchResult,
    UnsolicitedControlResult,
)
from .point_table import (
    POINT_TABLE_COLUMNS,
    POINT_TABLE_SCHEMA_VERSION,
    PointDefinition,
    PointTable,
    PointTableError,
    load_point_table,
)
from .performance import (
    PERFORMANCE_PROFILE_SCHEMA_VERSION,
    PerformanceProfile,
    PerformanceProfileError,
    PerformanceThresholds,
    ReadPerformanceScenario,
    SoakSettings,
    execute_read_only_iteration,
    load_performance_profile,
    nearest_rank,
    run_performance_suite,
)
from .process_metrics import ProcessResourceSample, ProcessResourceSampler
from .reporting import PersistedReport, write_json_report
from .safety_incidents import (
    SAFETY_INCIDENT_SCHEMA_VERSION,
    IncidentRecordResult,
    SafetyIncidentStore,
    dut_identity_sha256,
)
from .soak import SoakRunnerError, run_soak

__version__ = "0.6.1"
TARGET_STANDARD = "IEEE1815-2012"

__all__ = [
    "AnalogOutputCommand",
    "CaptureConfig",
    "CaptureEventManifest",
    "CapturePointRange",
    "CaptureResult",
    "ClientStateError",
    "CommandPointResult",
    "CommandTaskResult",
    "CrobCommand",
    "ControlCommand",
    "ControlScenario",
    "Dnp3ClientError",
    "Dnp3MasterClient",
    "EMS_TEST_PLAN_SCHEMA_VERSION",
    "EMS_PICS_STATUSES",
    "EMS_PROFILE_SCHEMA_VERSION",
    "EmsDeviceIdentity",
    "EmsProfile",
    "EmsProfileError",
    "EmsTestPlan",
    "EmsTestPlanError",
    "HostCommandError",
    "HostExitedError",
    "HostProcessConfig",
    "HostProcessDiagnostics",
    "HostProcessError",
    "HostProtocolError",
    "HostStartError",
    "HostTimeoutError",
    "LabSafetyConfig",
    "LOCAL_EVENT_PROFILE_SCHEMA_VERSION",
    "LocalEventLoad",
    "LocalEventProfile",
    "LocalEventProfileError",
    "MeasurementRecord",
    "POINT_TABLE_COLUMNS",
    "POINT_TABLE_SCHEMA_VERSION",
    "PERFORMANCE_PROFILE_SCHEMA_VERSION",
    "PerformanceProfile",
    "PerformanceProfileError",
    "PerformanceThresholds",
    "PersistedReport",
    "PointDefinition",
    "PointTable",
    "PointTableError",
    "PollScenario",
    "ReadHeader",
    "ReadPerformanceScenario",
    "ReadTaskResult",
    "SAFETY_INCIDENT_SCHEMA_VERSION",
    "SafetyIncidentAcknowledgmentError",
    "SafetyIncidentConfigurationError",
    "SafetyIncidentError",
    "SafetyIncidentPersistenceError",
    "SafetyIncidentStore",
    "SoakRunnerError",
    "SoakSettings",
    "TARGET_STANDARD",
    "TcpConnectionConfig",
    "UnsolicitedBatchResult",
    "UnsolicitedControlResult",
    "UnsolicitedScenario",
    "UnresolvedSafetyIncidentError",
    "IncidentRecordResult",
    "dut_identity_sha256",
    "execute_read_only_iteration",
    "load_ems_test_plan",
    "load_ems_profile",
    "load_local_event_profile",
    "load_point_table",
    "load_performance_profile",
    "nearest_rank",
    "ProcessResourceSample",
    "ProcessResourceSampler",
    "run_performance_suite",
    "run_local_event_benchmark",
    "run_soak",
    "write_json_report",
    "ValueExpectation",
    "__version__",
]
